#!/usr/bin/env python3
"""Generate editor-specific Black Ember palette artifacts from the TOML source."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PALETTE_PATH = ROOT / "palette" / "black-ember.toml"
NVIM_PALETTE_PATH = ROOT / "nvim" / "lua" / "black-ember" / "palette.lua"
VSCODE_THEME_PATH = ROOT / "vscode" / "themes" / "black-ember-color-theme.json"


def load_palette() -> dict:
    with PALETTE_PATH.open("rb") as palette_file:
        return tomllib.load(palette_file)


def render_lua(palette: dict) -> str:
    ui = palette["ui"]
    syntax = palette["syntax"]
    diagnostic = palette["diagnostic"]
    vcs = palette["vcs"]
    normal = palette["terminal"]["normal"]
    bright = palette["terminal"]["bright"]

    def table(name: str, values: dict, rename: dict[str, str] | None = None) -> list[str]:
        rename = rename or {}
        lines = [f"  {name} = {{"]
        for key, value in values.items():
            lines.append(f'    {rename.get(key, key)} = "{value}",')
        lines.append("  },")
        return lines

    def color_list(values: dict) -> str:
        return ", ".join(f'"{color}"' for color in values.values())

    lines = [
        "-- Generated by scripts/generate_themes.py from palette/black-ember.toml.",
        "-- Do not edit this file directly.",
        "return {",
    ]
    lines.extend(table("ui", ui))
    lines.extend(table("syntax", syntax, {"function": "function_"}))
    lines.extend(table("diagnostic", diagnostic))
    lines.extend(table("vcs", vcs))
    lines.extend(
        [
            "  terminal = {",
            f"    normal = {{ {color_list(normal)} }},",
            f"    bright = {{ {color_list(bright)} }},",
            "  },",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_vscode_theme(palette: dict) -> str:
    ui = palette["ui"]
    syntax = palette["syntax"]
    diagnostic = palette["diagnostic"]
    vcs = palette["vcs"]
    terminal = palette["terminal"]

    colors = {
        "focusBorder": ui["accent"],
        "foreground": ui["foreground"],
        "descriptionForeground": ui["muted"],
        "errorForeground": diagnostic["error"],
        "widget.shadow": ui["background_deep"],
        "selection.background": ui["overlay"],
        "textLink.foreground": ui["accent_secondary"],
        "textLink.activeForeground": ui["foreground_bright"],
        "textPreformat.foreground": syntax["string"],
        "button.background": ui["accent"],
        "button.foreground": ui["background"],
        "button.hoverBackground": ui["accent_secondary"],
        "button.secondaryBackground": ui["surface"],
        "button.secondaryForeground": ui["foreground"],
        "button.secondaryHoverBackground": ui["overlay"],
        "dropdown.background": ui["surface"],
        "dropdown.foreground": ui["foreground"],
        "dropdown.border": ui["border"],
        "input.background": ui["background_deep"],
        "input.foreground": ui["foreground"],
        "input.placeholderForeground": ui["muted"],
        "input.border": ui["border"],
        "inputOption.activeBorder": ui["accent"],
        "inputValidation.errorBackground": ui["background_deep"],
        "inputValidation.errorBorder": diagnostic["error"],
        "inputValidation.warningBackground": ui["background_deep"],
        "inputValidation.warningBorder": diagnostic["warning"],
        "inputValidation.infoBackground": ui["background_deep"],
        "inputValidation.infoBorder": diagnostic["info"],
        "badge.background": ui["accent"],
        "badge.foreground": ui["background"],
        "progressBar.background": ui["accent_secondary"],
        "titleBar.activeBackground": ui["background_deep"],
        "titleBar.activeForeground": ui["foreground"],
        "titleBar.inactiveBackground": ui["background_deep"],
        "titleBar.inactiveForeground": ui["muted"],
        "activityBar.background": ui["background_deep"],
        "activityBar.foreground": ui["foreground_bright"],
        "activityBar.inactiveForeground": ui["muted"],
        "activityBar.activeBorder": ui["accent"],
        "activityBarBadge.background": ui["accent"],
        "activityBarBadge.foreground": ui["background"],
        "sideBar.background": ui["background"],
        "sideBar.foreground": ui["foreground"],
        "sideBar.border": ui["border"],
        "sideBarTitle.foreground": ui["foreground_bright"],
        "sideBarSectionHeader.background": ui["background_deep"],
        "sideBarSectionHeader.foreground": ui["foreground"],
        "editorGroup.border": ui["border"],
        "editorGroupHeader.tabsBackground": ui["background_deep"],
        "editorGroupHeader.tabsBorder": ui["border"],
        "tab.activeBackground": ui["background"],
        "tab.activeForeground": ui["foreground_bright"],
        "tab.activeBorderTop": ui["accent"],
        "tab.inactiveBackground": ui["background_deep"],
        "tab.inactiveForeground": ui["muted"],
        "tab.hoverBackground": ui["surface"],
        "editor.background": ui["background"],
        "editor.foreground": ui["foreground"],
        "editorCursor.foreground": ui["cursor"],
        "editor.selectionBackground": ui["selection"],
        "editor.inactiveSelectionBackground": ui["overlay"],
        "editor.selectionHighlightBackground": ui["overlay"],
        "editor.wordHighlightBackground": ui["overlay"],
        "editor.wordHighlightStrongBackground": ui["surface"],
        "editor.lineHighlightBackground": ui["background_deep"],
        "editorLineNumber.foreground": syntax["punctuation"],
        "editorLineNumber.activeForeground": ui["accent_secondary"],
        "editorIndentGuide.background1": ui["surface"],
        "editorIndentGuide.activeBackground1": ui["overlay"],
        "editorWhitespace.foreground": ui["surface"],
        "editorRuler.foreground": ui["surface"],
        "editorBracketMatch.background": ui["overlay"],
        "editorBracketMatch.border": ui["accent_secondary"],
        "editor.findMatchBackground": ui["accent"],
        "editor.findMatchForeground": ui["background"],
        "editor.findMatchHighlightBackground": ui["overlay"],
        "editor.findRangeHighlightBackground": ui["surface"],
        "editor.hoverHighlightBackground": ui["surface"],
        "editorLink.activeForeground": ui["accent_secondary"],
        "editorWidget.background": ui["surface"],
        "editorWidget.foreground": ui["foreground"],
        "editorWidget.border": ui["border"],
        "editorSuggestWidget.background": ui["surface"],
        "editorSuggestWidget.foreground": ui["foreground"],
        "editorSuggestWidget.highlightForeground": ui["accent_secondary"],
        "editorSuggestWidget.selectedBackground": ui["overlay"],
        "editorHoverWidget.background": ui["surface"],
        "editorHoverWidget.foreground": ui["foreground"],
        "editorHoverWidget.border": ui["border"],
        "editorGutter.background": ui["background"],
        "editorGutter.addedBackground": vcs["added"],
        "editorGutter.modifiedBackground": vcs["modified"],
        "editorGutter.deletedBackground": vcs["removed"],
        "editorError.foreground": diagnostic["error"],
        "editorWarning.foreground": diagnostic["warning"],
        "editorInfo.foreground": diagnostic["info"],
        "editorHint.foreground": diagnostic["hint"],
        "editorOverviewRuler.errorForeground": diagnostic["error"],
        "editorOverviewRuler.warningForeground": diagnostic["warning"],
        "editorOverviewRuler.infoForeground": diagnostic["info"],
        "editorOverviewRuler.addedForeground": vcs["added"],
        "editorOverviewRuler.modifiedForeground": vcs["modified"],
        "editorOverviewRuler.deletedForeground": vcs["removed"],
        "diffEditor.insertedTextBackground": vcs["added"] + "33",
        "diffEditor.removedTextBackground": vcs["removed"] + "33",
        "diffEditor.insertedLineBackground": vcs["added"] + "1F",
        "diffEditor.removedLineBackground": vcs["removed"] + "1F",
        "list.activeSelectionBackground": ui["overlay"],
        "list.activeSelectionForeground": ui["foreground_bright"],
        "list.inactiveSelectionBackground": ui["surface"],
        "list.hoverBackground": ui["surface"],
        "list.highlightForeground": ui["accent_secondary"],
        "list.focusOutline": ui["accent"],
        "tree.indentGuidesStroke": ui["surface"],
        "panel.background": ui["background"],
        "panel.border": ui["border"],
        "panelTitle.activeForeground": ui["foreground_bright"],
        "panelTitle.activeBorder": ui["accent"],
        "panelTitle.inactiveForeground": ui["muted"],
        "statusBar.background": ui["surface"],
        "statusBar.foreground": ui["foreground"],
        "statusBar.border": ui["border"],
        "statusBar.debuggingBackground": diagnostic["warning"],
        "statusBar.debuggingForeground": ui["background"],
        "statusBar.noFolderBackground": ui["background_deep"],
        "statusBarItem.hoverBackground": ui["overlay"],
        "statusBarItem.prominentBackground": ui["accent"],
        "statusBarItem.prominentForeground": ui["background"],
        "terminal.background": ui["background"],
        "terminal.foreground": ui["foreground"],
        "terminalCursor.foreground": ui["cursor"],
        "terminal.selectionBackground": ui["selection"],
        "terminal.ansiBlack": terminal["normal"]["black"],
        "terminal.ansiRed": terminal["normal"]["red"],
        "terminal.ansiGreen": terminal["normal"]["green"],
        "terminal.ansiYellow": terminal["normal"]["yellow"],
        "terminal.ansiBlue": terminal["normal"]["blue"],
        "terminal.ansiMagenta": terminal["normal"]["magenta"],
        "terminal.ansiCyan": terminal["normal"]["cyan"],
        "terminal.ansiWhite": terminal["normal"]["white"],
        "terminal.ansiBrightBlack": terminal["bright"]["black"],
        "terminal.ansiBrightRed": terminal["bright"]["red"],
        "terminal.ansiBrightGreen": terminal["bright"]["green"],
        "terminal.ansiBrightYellow": terminal["bright"]["yellow"],
        "terminal.ansiBrightBlue": terminal["bright"]["blue"],
        "terminal.ansiBrightMagenta": terminal["bright"]["magenta"],
        "terminal.ansiBrightCyan": terminal["bright"]["cyan"],
        "terminal.ansiBrightWhite": terminal["bright"]["white"],
        "notificationCenter.border": ui["border"],
        "notifications.background": ui["surface"],
        "notifications.foreground": ui["foreground"],
        "notifications.border": ui["border"],
        "peekView.border": ui["accent"],
        "peekViewEditor.background": ui["background_deep"],
        "peekViewResult.background": ui["background"],
        "peekViewTitle.background": ui["surface"],
    }

    token_colors = [
        {"scope": ["comment", "punctuation.definition.comment"], "settings": {"foreground": syntax["comment"], "fontStyle": "italic"}},
        {"scope": ["string", "string.quoted", "string.template"], "settings": {"foreground": syntax["string"]}},
        {"scope": ["constant", "constant.language", "constant.character.escape"], "settings": {"foreground": syntax["constant"]}},
        {"scope": ["constant.numeric", "constant.language.boolean", "constant.language.null"], "settings": {"foreground": syntax["number"]}},
        {"scope": ["keyword", "storage", "storage.type", "keyword.control", "keyword.operator"], "settings": {"foreground": syntax["keyword"]}},
        {"scope": ["entity.name.function", "support.function", "meta.function-call"], "settings": {"foreground": syntax["function"]}},
        {"scope": ["entity.name.type", "entity.name.class", "support.type", "support.class"], "settings": {"foreground": syntax["type"]}},
        {"scope": ["variable", "variable.parameter"], "settings": {"foreground": syntax["variable"]}},
        {"scope": ["variable.other.property", "variable.other.object.property", "support.variable.property"], "settings": {"foreground": syntax["property"]}},
        {"scope": ["keyword.operator", "punctuation.accessor", "punctuation.separator"], "settings": {"foreground": syntax["operator"]}},
        {"scope": ["punctuation", "meta.brace", "meta.delimiter"], "settings": {"foreground": syntax["punctuation"]}},
        {"scope": ["entity.name.tag", "meta.tag", "support.class.component"], "settings": {"foreground": syntax["keyword"]}},
        {"scope": ["entity.other.attribute-name", "entity.other.attribute-name.html"], "settings": {"foreground": syntax["property"]}},
        {"scope": ["markup.heading", "entity.name.section"], "settings": {"foreground": ui["accent_secondary"], "fontStyle": "bold"}},
        {"scope": ["markup.bold"], "settings": {"fontStyle": "bold"}},
        {"scope": ["markup.italic"], "settings": {"fontStyle": "italic"}},
        {"scope": ["markup.inline.raw", "markup.fenced_code"], "settings": {"foreground": syntax["string"]}},
        {"scope": ["invalid", "invalid.illegal"], "settings": {"foreground": diagnostic["error"]}},
    ]

    semantic_tokens = {
        "comment": syntax["comment"],
        "string": syntax["string"],
        "number": syntax["number"],
        "regexp": syntax["property"],
        "keyword": syntax["keyword"],
        "operator": syntax["operator"],
        "function": syntax["function"],
        "method": syntax["function"],
        "type": syntax["type"],
        "class": syntax["type"],
        "interface": syntax["type"],
        "struct": syntax["type"],
        "enum": syntax["type"],
        "enumMember": syntax["constant"],
        "property": syntax["property"],
        "parameter": ui["foreground"],
        "variable": syntax["variable"],
        "namespace": syntax["type"],
        "decorator": syntax["property"],
    }

    theme = {
        "$schema": "vscode://schemas/color-theme",
        "name": palette["meta"]["name"],
        "type": palette["meta"]["variant"],
        "semanticHighlighting": True,
        "colors": colors,
        "tokenColors": token_colors,
        "semanticTokenColors": semantic_tokens,
    }
    return json.dumps(theme, indent=2) + "\n"


def expected_outputs(palette: dict) -> dict[Path, str]:
    return {
        NVIM_PALETTE_PATH: render_lua(palette),
        VSCODE_THEME_PATH: render_vscode_theme(palette),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    outputs = expected_outputs(load_palette())
    stale_files = []

    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale_files.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    if stale_files:
        for path in stale_files:
            print(f"Generated file is stale: {path}", file=sys.stderr)
        print("Run: python3 scripts/generate_themes.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
